services:
  chromadb:
    build:
      context: .
      dockerfile: ./Dockerfile-chromadb
    ports:
      - 8000:8000
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8001" ]
      interval: 30s
      timeout: 10s
      retries: 3

    depends_on:
      index-init:
        condition: service_completed_successfully # Let the init container create index first 


  index-init:
    build:
      context: .
      dockerfile: ./Dockerfile-indexing
    env_file: .env
    environment:
      - DATA_GITBOOK_SITE=${DATA_GITBOOK_SITE}
      - DATA_TASK=${DATA_TASK}