apiVersion: v1
kind: Namespace
metadata:
  name: socialbiz-gitbook-chatbot

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot
  namespace: socialbiz-gitbook-chatbot

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chatbot-role
  namespace: socialbiz-gitbook-chatbot
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chatbot-binding
  namespace: socialbiz-gitbook-chatbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chatbot-role
subjects:
  - kind: ServiceAccount
    name: chatbot
    namespace: socialbiz-gitbook-chatbot
