apiVersion: v1
kind: Service
metadata:
  name: socialbiz-chromadb-service
  namespace: socialbiz-gitbook-chatbot
spec:
  type: NodePort
  selector:
    app: socialbiz-chromadb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialbiz-chromadb
  namespace: socialbiz-gitbook-chatbot
  labels:
    app: socialbiz-chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialbiz-chromadb
  template:
    metadata:
      labels:
        app: socialbiz-chromadb
    spec:
      containers:
        - name: socialbiz-chromadb-container
          image: 494056189061.dkr.ecr.ap-northeast-2.amazonaws.com/socialbiz-chromadb:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: chromadb-secret
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: socialbiz-chromadb-autoscaler
  namespace: socialbiz-gitbook-chatbot
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 1
  maxReplicas: 1
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 2
        - periodSeconds: 60
          type: Percent
          value: 50
      selectPolicy: Max
    scaleUp:
      policies:
        - periodSeconds: 15
          type: Pods
          value: 1
        - periodSeconds: 15
          type: Percent
          value: 100
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: socialbiz-chromadb
