apiVersion: v1
kind: Service
metadata:
  name: socialbiz-be-service
  namespace: socialbiz-gitbook-chatbot
spec:
  type: NodePort
  selector:
    app: socialbiz-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialbiz-be
  namespace: socialbiz-gitbook-chatbot
  labels:
    app: socialbiz-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialbiz-be
  template:
    metadata:
      labels:
        app: socialbiz-be
    spec:
      containers:
        - name: socialbiz-be-container
          image: 494056189061.dkr.ecr.ap-northeast-2.amazonaws.com/socialbiz-be:latest
          command: ["sh", "-c"]
          args: ["-c", "while true; do sleep 3600; done"]
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8989
          volumeMounts:
            - name: config-volume
              mountPath: /app/.env
              subPath: .env
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
      volumes:
        - name: config-volume
          configMap:
            name: be-secret
            items:
              - key: .env
                path: .env
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: socialbiz-be-autoscaler
  namespace: socialbiz-gitbook-chatbot
spec:
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 1
  maxReplicas: 1
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 2
        - periodSeconds: 60
          type: Percent
          value: 50
      selectPolicy: Max
    scaleUp:
      policies:
        - periodSeconds: 15
          type: Pods
          value: 1
        - periodSeconds: 15
          type: Percent
          value: 100
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: socialbiz-be
